// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAruEbugO12JcdDvnk8Uw9jVaJtEgyvIPo',
    appId: '1:71541354951:web:60ff63746c690417b229e2',
    messagingSenderId: '71541354951',
    projectId: 'campuscore-d435e',
    authDomain: 'campuscore-d435e.firebaseapp.com',
    databaseURL: 'https://campuscore-d435e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campuscore-d435e.firebasestorage.app',
    measurementId: 'G-3WFRFPCN7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgsATRyk5mxUQOjaazl4RebkfscIiQxjc',
    appId: '1:71541354951:android:2b5005aa2a9868b7b229e2',
    messagingSenderId: '71541354951',
    projectId: 'campuscore-d435e',
    databaseURL: 'https://campuscore-d435e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campuscore-d435e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhH-PyQ_xYngOm0Hr7AcXWbJ4Oupst1Kg',
    appId: '1:71541354951:ios:b8667586f3fac652b229e2',
    messagingSenderId: '71541354951',
    projectId: 'campuscore-d435e',
    databaseURL: 'https://campuscore-d435e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campuscore-d435e.firebasestorage.app',
    iosClientId: '71541354951-djqp8t82jj2cjd6kktefpl69701p3qvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhH-PyQ_xYngOm0Hr7AcXWbJ4Oupst1Kg',
    appId: '1:71541354951:ios:b8667586f3fac652b229e2',
    messagingSenderId: '71541354951',
    projectId: 'campuscore-d435e',
    databaseURL: 'https://campuscore-d435e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campuscore-d435e.firebasestorage.app',
    iosClientId: '71541354951-djqp8t82jj2cjd6kktefpl69701p3qvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAruEbugO12JcdDvnk8Uw9jVaJtEgyvIPo',
    appId: '1:71541354951:web:c5bf64f1b76c7119b229e2',
    messagingSenderId: '71541354951',
    projectId: 'campuscore-d435e',
    authDomain: 'campuscore-d435e.firebaseapp.com',
    databaseURL: 'https://campuscore-d435e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campuscore-d435e.firebasestorage.app',
    measurementId: 'G-BCFS53E48J',
  );
}
